Update checkbashism-native to 2.23.7
priv-kweihmann/meta-sca pull request #12148
Opened 2024-07-17 21:33 UTC by ryan09274

Closes #11849

2024-07-17 21:48 UTC, ryan09274 commented
Similar to #11797, this is a cherry pick of Konrad's commit https://github.com/priv-kweihmann/meta-sca/commit/eea7f86694f33d5715c72073ceb7ba03d5751943 from the master branch to the kirkstone branch.

There is currently a fetch error when using the meta-sca kirkstone branch due to devscripts_2.23.6.tar.xz file no longer at the SRC_URI site (http://deb.debian.org/debian/pool/main/d/devscripts/devscripts_2.23.6.tar.xz). The following files are currently listed on the site: `devscripts_2.23.4+deb12u1.tar.xz`, `devscripts_2.23.6~bpo11+1.tar.xz`, and `devscripts_2.23.7.tar.xz`. In addition, I'm wondering if `devscripts_2.23.6~bpo11+1.tar.xz` can also be used instead?

2024-07-18 13:06 UTC, priv-kweihmann requested changes

2024-07-18 13:06 UTC, priv-kweihmann commented on recipes-sca/checkbashism-native/nativesdk-checkbashism_2.23.7.bb
> +SUMMARY = "check for bashisms in /bin/sh scripts"
Nativesdk support is not available on Kirkstone - please remove the recipe

2024-07-19 01:35 UTC, ryan09274 commented
Pushed changes on kirkstone branch to remove nativesdk-checkbashism_2.23.7.bb

2024-07-19 05:59 UTC, priv-kweihmann approved these changes

2024-07-19 05:59 UTC, merged